open Ctypes
open Yolo.C

let keep x = ignore (Sys.opaque_identity (List.hd [ x ]))
let getfp p field = !@(p |-> field)
let to_string t = Ctypes.(coerce (ptr char) string t)
let print pp t = Format.printf "@[%a@]@.%!" pp t

let%expect_test "yolo" =
  let model = make Types.model_t in
  let fname = "models/yolov3-tiny.gguf" in
  let rc = Functions.model_init (addr model) fname in
  assert (rc = 0);
  let yolo = Functions.model_graph @@ addr model in
  let nodes = Ggml.C.Functions.graph_n_nodes yolo in
  Format.printf "nodes:%u" nodes;
  [%expect "nodes:213"];
  let open Ggml_model_explorer in
  print TensorId.pp_nodes @@ TensorId.of_graph yolo;
  [%expect
    {|
      {id:0; kind:Intermediate}
      {id:1; kind:Intermediate}
      {id:2; kind:Intermediate}
      {id:3; kind:Intermediate}
      {id:4; kind:Intermediate}
      {id:5; kind:Intermediate}
      {id:6; kind:Intermediate}
      {id:7; kind:Intermediate}
      {id:8; kind:Intermediate}
      {id:9; kind:Intermediate}
      {id:10; kind:Intermediate}
      {id:11; kind:Intermediate}
      {id:12; kind:Intermediate}
      {id:13; kind:Intermediate}
      {id:14; kind:Intermediate}
      {id:15; kind:Intermediate}
      {id:16; kind:Intermediate}
      {id:17; kind:Intermediate}
      {id:18; kind:Intermediate}
      {id:19; kind:Intermediate}
      {id:20; kind:Intermediate}
      {id:21; kind:Intermediate}
      {id:22; kind:Intermediate}
      {id:23; kind:Intermediate}
      {id:24; kind:Intermediate}
      {id:25; kind:Intermediate}
      {id:26; kind:Intermediate}
      {id:27; kind:Intermediate}
      {id:28; kind:Intermediate}
      {id:29; kind:Intermediate}
      {id:30; kind:Intermediate}
      {id:31; kind:Intermediate}
      {id:32; kind:Intermediate}
      {id:33; kind:Intermediate}
      {id:34; kind:Intermediate}
      {id:35; kind:Intermediate}
      {id:36; kind:Intermediate}
      {id:37; kind:Intermediate}
      {id:38; kind:Intermediate}
      {id:39; kind:Intermediate}
      {id:40; kind:Intermediate}
      {id:41; kind:Intermediate}
      {id:42; kind:Intermediate}
      {id:43; kind:Intermediate}
      {id:44; kind:Intermediate}
      {id:45; kind:Intermediate}
      {id:46; kind:Intermediate}
      {id:47; kind:Intermediate}
      {id:48; kind:Intermediate}
      {id:49; kind:Intermediate}
      {id:50; kind:Intermediate}
      {id:51; kind:Intermediate}
      {id:52; kind:Intermediate}
      {id:53; kind:Intermediate}
      {id:54; kind:Intermediate}
      {id:55; kind:Intermediate}
      {id:56; kind:Intermediate}
      {id:57; kind:Intermediate}
      {id:58; kind:Intermediate}
      {id:59; kind:Intermediate}
      {id:60; kind:Intermediate}
      {id:61; kind:Intermediate}
      {id:62; kind:Intermediate}
      {id:63; kind:Intermediate}
      {id:64; kind:Intermediate}
      {id:65; kind:Intermediate}
      {id:66; kind:Intermediate}
      {id:67; kind:Intermediate}
      {id:68; kind:Intermediate}
      {id:69; kind:Intermediate}
      {id:70; kind:Intermediate}
      {id:71; kind:Intermediate}
      {id:72; kind:Intermediate}
      {id:73; kind:Intermediate}
      {id:74; kind:Intermediate}
      {id:75; kind:Intermediate}
      {id:76; kind:Intermediate}
      {id:77; kind:Intermediate}
      {id:78; kind:Intermediate}
      {id:79; kind:Intermediate}
      {id:80; kind:Intermediate}
      {id:81; kind:Intermediate}
      {id:82; kind:Intermediate}
      {id:83; kind:Intermediate}
      {id:84; kind:Intermediate}
      {id:85; kind:Intermediate}
      {id:86; kind:Intermediate}
      {id:87; kind:Intermediate}
      {id:88; kind:Intermediate}
      {id:89; kind:Intermediate}
      {id:90; kind:Intermediate}
      {id:91; kind:Intermediate}
      {id:92; kind:Intermediate}
      {id:93; kind:Intermediate}
      {id:94; kind:Intermediate}
      {id:95; kind:Intermediate}
      {id:96; kind:Intermediate}
      {id:97; kind:Intermediate}
      {id:98; kind:Intermediate}
      {id:99; kind:Intermediate}
      {id:100; kind:Intermediate}
      {id:101; kind:Intermediate}
      {id:102; kind:Intermediate}
      {id:103; kind:Intermediate}
      {id:104; kind:Intermediate}
      {id:105; kind:Intermediate}
      {id:106; kind:Intermediate}
      {id:107; kind:Intermediate}
      {id:108; kind:Intermediate}
      {id:109; kind:Intermediate}
      {id:110; kind:Intermediate}
      {id:111; kind:Intermediate}
      {id:112; kind:Intermediate}
      {id:113; kind:Intermediate}
      {id:114; kind:Intermediate}
      {id:115; kind:Intermediate}
      {id:116; kind:Intermediate}
      {id:117; kind:Intermediate}
      {id:118; kind:Intermediate}
      {id:119; kind:Intermediate}
      {id:120; kind:Intermediate}
      {id:121; kind:Intermediate}
      {id:122; kind:Intermediate}
      {id:123; kind:Intermediate}
      {id:124; kind:Intermediate}
      {id:125; kind:Intermediate}
      {id:126; kind:Intermediate}
      {id:127; kind:Intermediate}
      {id:128; kind:Intermediate}
      {id:129; kind:Intermediate}
      {id:130; kind:Intermediate}
      {id:131; kind:Intermediate}
      {id:132; kind:Intermediate}
      {id:133; kind:Intermediate}
      {id:134; kind:Intermediate}
      {id:135; kind:Intermediate}
      {id:136; kind:Intermediate}
      {id:137; kind:Intermediate}
      {id:138; kind:Intermediate}
      {id:139; kind:Intermediate}
      {id:140; kind:Intermediate}
      {id:141; kind:Intermediate}
      {id:142; kind:Intermediate}
      {id:143; kind:Intermediate}
      {id:144; kind:Intermediate}
      {id:145; kind:Intermediate}
      {id:146; kind:Intermediate}
      {id:147; kind:Intermediate}
      {id:148; kind:Intermediate}
      {id:149; kind:Intermediate}
      {id:150; kind:Intermediate}
      {id:151; kind:Intermediate}
      {id:152; kind:Intermediate}
      {id:153; kind:Intermediate}
      {id:154; kind:Intermediate}
      {id:155; kind:Intermediate}
      {id:156; kind:Intermediate}
      {id:157; kind:Intermediate}
      {id:158; kind:Intermediate}
      {id:159; kind:Intermediate}
      {id:160; kind:Intermediate}
      {id:161; kind:Intermediate}
      {id:162; kind:Intermediate}
      {id:163; kind:Intermediate}
      {id:164; kind:Intermediate}
      {id:165; kind:Intermediate}
      {id:166; kind:Intermediate}
      {id:167; kind:Output}
      {id:168; kind:Intermediate}
      {id:169; kind:Intermediate}
      {id:170; kind:Intermediate}
      {id:171; kind:Intermediate}
      {id:172; kind:Intermediate}
      {id:173; kind:Intermediate}
      {id:174; kind:Intermediate}
      {id:175; kind:Intermediate}
      {id:176; kind:Intermediate}
      {id:177; kind:Intermediate}
      {id:178; kind:Intermediate}
      {id:179; kind:Intermediate}
      {id:180; kind:Intermediate}
      {id:181; kind:Intermediate}
      {id:182; kind:Intermediate}
      {id:183; kind:Intermediate}
      {id:184; kind:Intermediate}
      {id:185; kind:Intermediate}
      {id:186; kind:Intermediate}
      {id:187; kind:Intermediate}
      {id:188; kind:Intermediate}
      {id:189; kind:Intermediate}
      {id:190; kind:Intermediate}
      {id:191; kind:Intermediate}
      {id:192; kind:Intermediate}
      {id:193; kind:Intermediate}
      {id:194; kind:Intermediate}
      {id:195; kind:Intermediate}
      {id:196; kind:Intermediate}
      {id:197; kind:Intermediate}
      {id:198; kind:Intermediate}
      {id:199; kind:Intermediate}
      {id:200; kind:Intermediate}
      {id:201; kind:Intermediate}
      {id:202; kind:Intermediate}
      {id:203; kind:Intermediate}
      {id:204; kind:Intermediate}
      {id:205; kind:Intermediate}
      {id:206; kind:Intermediate}
      {id:207; kind:Intermediate}
      {id:208; kind:Intermediate}
      {id:209; kind:Intermediate}
      {id:210; kind:Intermediate}
      {id:211; kind:Intermediate}
      {id:212; kind:Output}
      {id:213; kind:Constant}
      {id:214; kind:Constant}
      {id:215; kind:Constant}
      {id:216; kind:Constant}
      {id:217; kind:Constant}
      {id:218; kind:Constant}
      {id:219; kind:Constant}
      {id:220; kind:Constant}
      {id:221; kind:Constant}
      {id:222; kind:Constant}
      {id:223; kind:Constant}
      {id:224; kind:Constant}
      {id:225; kind:Constant}
      {id:226; kind:Constant}
      {id:227; kind:Constant}
      {id:228; kind:Constant}
      {id:229; kind:Constant}
      {id:230; kind:Constant}
      {id:231; kind:Constant}
      {id:232; kind:Constant}
      {id:233; kind:Constant}
      {id:234; kind:Constant}
      {id:235; kind:Constant}
      {id:236; kind:Constant}
      {id:237; kind:Constant}
      {id:238; kind:Constant}
      {id:239; kind:Constant}
      {id:240; kind:Constant}
      {id:241; kind:Constant}
      {id:242; kind:Constant}
      {id:243; kind:Constant}
      {id:244; kind:Constant}
      {id:245; kind:Constant}
      {id:246; kind:Constant}
      {id:247; kind:Constant}
      {id:248; kind:Constant}
      {id:249; kind:Constant}
      {id:250; kind:Constant}
      {id:251; kind:Constant}
      {id:252; kind:Constant}
      {id:253; kind:Constant}
      {id:254; kind:Constant}
      {id:255; kind:Constant}
      {id:256; kind:Constant}
      {id:257; kind:Constant}
      {id:258; kind:Constant}
      {id:259; kind:Constant}
      {id:260; kind:Constant}
      {id:261; kind:Constant}
      {id:262; kind:Constant}
      {id:263; kind:Constant}
      {id:264; kind:Constant}
      {id:265; kind:Constant}
      {id:266; kind:Constant}
      {id:267; kind:Constant}
      {id:268; kind:Constant}
      {id:269; kind:Constant}
      {id:270; kind:Constant}
      {id:271; kind:Constant}
      {id:272; kind:Constant}
    |}];
  Functions.model_uninit @@ addr model;
  keep model;
  ()
